export const SET_OVERLAY = 'MAIN/SET_OVERLAY';
export const SET_TOP_USERS = 'MAIN/SET_TOP_USERS';
export const SET_UPDATE = 'MAIN/SET_UPDATE';
export const SET_CLOSE_DIALOG_LOADING = 'MAIN/SET_CLOSE_DIALOG_LOADING';
export const SET_NOT_FOUND = 'MAIN/SET_NOT_FOUND';
export const SET_CLOSE_NOT_FOUND_LOADING = 'MAIN/SET_CLOSE_NOT_FOUND_LOADING';
export const SET_ANIME = 'MAIN/SET_ANIME';