export const SET_OVERLAY = 'MAIN/SET_OVERLAY';
export const SET_TOP_USERS = 'MAIN/SET_TOP_USERS';
export const SET_UPDATE = 'MAIN/SET_UPDATE';
export const SET_CLOSE_DIALOG_LOADING = 'MAIN/SET_CLOSE_DIALOG_LOADING';